### ISSUE TITLE
Error: Cannot find module 'true' from

### ISSUE THREAD

**Issue by aristidesfl** [ben-ng/minifyify#120]
I get this error when I try to pass options with --uglify. 
Tried other options too. 
It works fine without --uglify.

```
$ npm run minifyify

> test@1.0.0 minifyify /Users/user/Work/test
> browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js

/Users/user/Work/test/node_modules/resolve/lib/sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
    ^

Error: Cannot find module 'true' from '/Users/user/Work/test'
    at Function.module.exports [as sync] (/Users/user/Work/test/node_modules/resolve/lib/sync.js:33:11)
    at Browserify.plugin (/Users/user/Work/test/node_modules/browserify/index.js:354:29)
    at /Users/user/Work/test/node_modules/browserify/bin/args.js:126:15
    at Array.forEach (native)
    at module.exports (/Users/user/Work/test/node_modules/browserify/bin/args.js:121:10)
    at Object.<anonymous> (/Users/user/Work/test/node_modules/browserify/bin/cmd.js:6:26)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/bin/npm" "run" "minifyify"
npm ERR! node v5.4.1
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 minifyify: `browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 minifyify script 'browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Work/test/npm-debug.log
```
npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.4.1_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'minifyify' ]
2 info using npm@3.7.1
3 info using node@v5.4.1
4 verbose run-script [ 'preminifyify', 'minifyify', 'postminifyify' ]
5 info lifecycle test@1.0.0~preminifyify: test@1.0.0
6 silly lifecycle test@1.0.0~preminifyify: no script for preminifyify, continuing
7 info lifecycle test@1.0.0~minifyify: test@1.0.0
8 verbose lifecycle test@1.0.0~minifyify: unsafe-perm in lifecycle true
9 verbose lifecycle test@1.0.0~minifyify: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/user/Work/test/node_modules/.bin:/usr/local/Cellar/node/5.4.1_1/bin:/Users/user/.rbenv/shims:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:.:/Users/user/Dropbox/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin
10 verbose lifecycle test@1.0.0~minifyify: CWD: /Users/user/Work/test
11 silly lifecycle test@1.0.0~minifyify: Args: [ '-c',
11 silly lifecycle   'browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js' ]
12 silly lifecycle test@1.0.0~minifyify: Returned: code: 1  signal: null
13 info lifecycle test@1.0.0~minifyify: Failed to exec minifyify script
14 verbose stack Error: test@1.0.0 minifyify: `browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid test@1.0.0
16 verbose cwd /Users/user/Work/test
17 error Darwin 15.4.0
18 error argv "/usr/local/Cellar/node/5.4.1_1/bin/node" "/usr/local/bin/npm" "run" "minifyify"
19 error node v5.4.1
20 error npm  v3.7.1
21 error code ELIFECYCLE
22 error test@1.0.0 minifyify: `browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js`
22 error Exit status 1
23 error Failed at the test@1.0.0 minifyify script 'browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs test
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls test
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by laszlokorte** [comment]
@aristidesfl I spend 3 hours fighting with that problem. In the end the problem for me was a missing space between the two closing brackets of the subarg syntax (`]]`).

```
browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress]] > index.js
```
vs
```
browserify index.coffee --debug -t coffeeify -p [minifyify --output index.js.map --uglify [--compress] ] > index.js
```
(the space at `[--compress] ]` is important)

**Comment by ben-ng** [comment]
Glad you figured it out! Browserify parses the arguments, not minifyify, so if you want a better error message you should open an issue in Browserify's argument parser.
