### ISSUE TITLE
'Error: Invalid mapping' after babel upgrade

### ISSUE THREAD

**Issue by sajinshrestha** [ben-ng/minifyify#124]
After successfully upgrading from Babel 5 to 6, `minifyify --map` is throwing following error. 

usage:
```
browserify entry.jsx -d -p [minifyify --map bundle.js.map --output bundle.js.map] > bundle.js

````

```
main_folder/node_modules/minifyify/node_modules/source-map/lib/source-map-generator.js:277
      throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":273,"column":55},"source":"entry.jsx","original":{"line":null,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (main_folder/node_modules/minifyify/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (main_folder/node_modules/minifyify/node_modules/source-map/lib/source-map-generator.js:101:12)
    at main_folder/node_modules/minifyify/lib/minifier.js:391:17
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (main_folder/node_modules/minifyify/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at main_folder/node_modules/minifyify/lib/minifier.js:382:13
    at main_folder/node_modules/minifyify/lib/minifier.js:429:5
    at main_folder/node_modules/lodash._baseeach/index.js:182:11
    at baseForOwn (main_folder/node_modules/lodash._baseeach/index.js:93:20)
    at main_folder/node_modules/lodash._baseeach/index.js:151:14
```

minify without generating source maps works.
```
browserify entry.jsx -d -p [minifyify --no-map] > bundle.js
```
Using: 
- node@v5.6.0
- npm@3.6.0
- browserify@13.0.1
- minifyify@7.3.3

Any ideas on how to troubleshoot this?

**Comment by sajinshrestha** [comment]
Never mind. After rebuilding `npm-shrinkwrap.json` file, this issue is fixed .
