### ISSUE TITLE
uglify-js failed on client.js : SyntaxError: Unexpected token punc «,», expected punc «:»

### ISSUE THREAD

**Issue by digitalmouse** [ben-ng/minifyify#127]
Greetings!  Maybe my issue is similar to the other 'Unexpected token' issue, but I'll post it here as it might be considered a separate issue.

For my project, minifyify with the uglify option was working just fine, until I started use the Vue.js 2 vue-router packages.

Now, when I transmogrify everything, the uglify option complains with a slightly confusing error: 

```
uglify-js failed on client.js : SyntaxError: Unexpected token punc «,», expected punc «:» (line: 37, col: 8, pos: 1360)

Error
    at new JS_Parse_Error (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)
    at token_error (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)
    at expect_token (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:9)
    at expect (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2116:36)
    at eval (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2689:13)
    at eval (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2139:24)
    at expr_atom (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2619:35)
    at maybe_unary (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2795:19)
    at expr_ops (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2830:24)
    at maybe_conditional (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2835:20)
    at maybe_assign (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2859:20)
    at expression (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2878:20)
    at expr_list (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2644:24)
    at new_ (eval at <anonymous> (/home/jip/projects/JSTurfClient/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2544:20)
```

The code in question is a route definition:

```
const router = new VueRouter({
  routes: [
    { path: '/login'       , component: Login },
    { path: '/devicelist'  , component: DeviceList },
    { path: '/main'        , component: Main,
      children: [
        { path: 'Weather'  , component: Weather },
        { path: 'Programs' , component: Programs },
        { path: 'Stations' , component: Stations },
        { path: 'History'  , component: History },
        { path: 'Setup'    , component: Setup }
      ]
    }
  ]
});
```

Line 37 is the  `{ path: 'Programs' , component: Programs },` line.  Runs just fine without minifyifying, and oddly enough _**even with the error, the minifyifying still completes and i get a functioning build.js file which runs without problems on the client-side.**_  It just isn't uglified.

My browserify setup (with the miniflyify plugin) reads as follows:

```
browserify( { debug: true } )
  .add( 'client.js' )
  .transform( 'vueify' )
  .transform( 'babelify' )
  .plugin( 'minifyify' , {
    map: false, 
    uglify: {
      compress: {
        drop_console: true,
        dead_code: true,
        conditionals: true,
        unused: true,
        if_return: true,
        global_defs: {
          DEBUG: false
        }
      },
      mangle: true,
      'screw-ie8': true
    }
  })
  .bundle()
  .on('error', function (err) {
    console.log(err);
  })
  .pipe( fs.createWriteStream( './public/javascripts/build.js' )
);
```

Any thoughts on if it's me or minifyify would be greatly appreciated!

**Comment by digitalmouse** [comment]
After some extra digging, I found a gulp-minify related issue with the same problem, but not using the Vue.js router.  In that case, commenters mention that the `const router =` stuff was ES6 and the minifying did not support ES6. Just for fun, I changed my code to use `var`, but made no difference.

**Comment by ben-ng** [comment]
I don't think that this is a minifyify issue -- minifyify relies on uglify to parse code, so if something doesn't support ES6, it's uglify.
