### ISSUE TITLE
Crashes when building

### ISSUE THREAD

**Issue by katyo** [ben-ng/minifyify#98]
I got an error when try to build my project:
```
node_modules/minifyify/lib/minifier.js:255
  if(opts._ !== undefined) delete opts._;
         ^
TypeError: Cannot read property '_' of null
  at [object Object].Minifier.sanitizeObject (node_modules/minifyify/lib/minifier.js:255:10)
  at [object Object].Minifier.sanitizeObject (node_modules/minifyify/lib/minifier.js:258:12)
  at [object Object].Minifier.sanitizeObject (node_modules/minifyify/lib/minifier.js:258:12)
  at finish (node_modules/minifyify/lib/minifier.js:170:16)
  at node_modules/minifyify/lib/minifier.js:199:11
  at Object.oncomplete (fs.js:107:15)
```

My browserify commandline:
```
browserify -t coffeeify --extension=.coffee -t [envify --NODE_ENV="$NODE_ENV" --BUILD_TYPE=release] -d client.coffee -o dist/js/client.min.js -p [minifyify --map client.min.js.map --output dist/js/client.min.js.map --compressPath "$PWD" --uglify [ --mangle [ --toplevel ] --compress [ --evaluate --sequences --drop_console --unsafe --hoist_vars ] ] ]
```

I applied the next patch to `lib/minifier.js` to fix this issue:
```
257c257
<     if(typeof opts[key] === 'object') {
---
>     if(typeof opts[key] === 'object' && opts[key] !== null) {
```

**Comment by ben-ng** [comment]
Thanks!
